name: CI

on: [push]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Code Quality
        run: bun run quality
